title: "Clémence Pougué"
url: "https://clemencepougue.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "contrast"
locale: "en-GB"

author:
  name: "Clémence Pougué"
  avatar: "/assets/img/avatar.jpg"
  bio: "Economist. Expert in impact evaluations of interventions, legal and policy reforms improving human capital and women's economic empowerment."
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope"
      url: "mailto:cpouguebiyong@worldbank.org"
    - label: Google Scholar
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=H5azOdEAAAAJ&hl=fr&oi=ao"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/clemencepougue"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
